In [125]:
import cv2
import time
import numpy

cap = cv2.VideoCapture(1)
start_time = time.time()
frame_count=0

while(True):
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blue,green,red = cv2.split(frame)
    print(gray)
    frame_count += 1
    elapsed_time = time.time() - start_time
    fps = frame_count / elapsed_time
    print(fps)
    cv2.putText(frame, f"FPS: {fps:.2f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    
    _, _, _, max_locg = cv2.minMaxLoc(gray)
    cv2.circle(frame,max_locg,10,(0,0,0),-1)
    
    
    red_mask = cv2.inRange(frame, (0,0,100), (50,50,255))
    max_logr = numpy.unravel_index(numpy.argmax(numpy.ma.masked_where(red_mask == 0, red)), red.shape)

  
    cv2.circle(frame, max_logr, 10,(0,0, 255), -1)


    #Part 6
    # max_intensity = 0
    # max_loc = (0, 0)

    # for y in range(frame.shape[0]):
    #     for x in range(frame.shape[1]):
    #         intensity = gray[y, x]
    #         if intensity > max_intensity:
    #             max_intensity = intensity
    #             max_loc = (x, y)

    # cv2.circle(frame, max_loc, 30, (0, 255, 0))
    
    
    
    cv2.imshow('frame', frame)
    #cv2.imshow('gray',gray)
    #cv2.imshow('red',red)
    
    
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
11.018562594244703
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15.192184958871064
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
19.659264119990628
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
21.915932313206866
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
23.42684027560568
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
24.35657673788381
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
25.15658793842832
[[0 0 0 ... 0 0 0]
 [0 0 0 ...